### ISSUE TITLE
node packages vulnerabilities

### ISSUE THREAD

**Issue by kanava-ali** [ishanvyas22/asset-mix#28]
Existing node package dependencies require updatating due to found vulnerabilites when running npm install.

**Comment by ishanvyas22** [comment]
Thanks @kanava-ali for opening up an issue. Will you be able to submit a PR to solve this?

**Comment by kanava-ali** [comment]
I will do it next week as I am starting my weekend. Cheers for
quick response.

**Comment by kanava-ali** [comment]
I managed to solve this issue by running a "npm audit fix --force" command and updating the dependencies however the asse-mix command which generates the dependencies are quite new to me therefore I will not make any pull request to fix it.
