### ISSUE TITLE
Additional information for server-side setup: must disable Cake asset timestamping

### ISSUE THREAD

**Issue by jrbakooba** [ishanvyas22/asset-mix#39]
**Is your feature request related to a problem? Please describe.**
Yes, a problem I had while setting up this library on a Cake3 application. With asset timestamping (`Asset.timestamp => true or 'force'` in app.php) enabled, AssetMix will fail to find the manifest. This is because Cake appends a timestamp to the end of the asset URL which means the "path" is not found in the mix manifest.

I'm new to this plugin and to mix/manifests in general, so I apologize if my terminology is inaccurate.

**Describe the solution you'd like**
Either update the docs to indicate that this setting should be turned off OR find a way for the manifest loader to ignore the timestamp in the query string when loading the asset file.

**Describe alternatives you've considered**
N/A

**Additional context**
![Screen Shot 2022-04-29 at 10 30 35](https://user-images.githubusercontent.com/44233922/165965551-1bf2dbaa-41b1-4c14-b165-0f09ca52847c.png)

**Comment by jrbakooba** [comment]
Sure, happy to put together a PR.

Do you think it makes the most sense to just check for the query string and strip it? Or should we try to be cleverer about it somehow? I'm brand-new to the library so I'm not sure of the full scope of what the right fix might be.

Ideas welcome, and I can write the patch.

**Comment by ishanvyas22** [comment]
Yeah, just checking for query string and strip out the content after it would work as of now.

**Comment by jrbakooba** [comment]
@ishanvyas22 I've added tests to my branch, many apologies for the delay.

**Comment by ishanvyas22** [comment]
Fixed for CakePHP 3. Need to port to CakePHP 4.x.
